//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: gui.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CODELITEPROJECTS_CODELITE_WXWIDGETS_DIV2_DEMO_GUI_BASE_CLASSES_H
#define _CODELITEPROJECTS_CODELITE_WXWIDGETS_DIV2_DEMO_GUI_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class MainFrameBase : public wxFrame
{
protected:
    wxStaticText* m_staticText1;
    wxTextCtrl* m_textCtrl1;
    wxTextCtrl* m_textCtrl2;
    wxButton* m_button1;
    wxStaticText* m_staticText2;

protected:
    virtual void OnCloseFrame(wxCloseEvent& event) { event.Skip(); }
    virtual void myClick(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText1() { return m_staticText1; }
    wxTextCtrl* GetTextCtrl1() { return m_textCtrl1; }
    wxTextCtrl* GetTextCtrl2() { return m_textCtrl2; }
    wxButton* GetButton1() { return m_button1; }
    wxStaticText* GetStaticText2() { return m_staticText2; }
    MainFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("TSN"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(125,217), long style = wxCAPTION|wxCLOSE_BOX|wxTAB_TRAVERSAL);
    virtual ~MainFrameBase();
};

#endif
